<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var $block \Webto\EAN\Block\Form\Ean
 */
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset items <?php /* @noEscape */ echo $methodCode ?>" id="payment_form_<?php /* @noEscape */ echo $methodCode ?>" style="display: none">
    <div class="field number required">
        <label for="ean_number" class="label"><span><?php echo $block->escapeHtml(__('EAN-Nummer')) ?></span></label>
        <div class="control">
            <input type="text" id="ean_number" name="payment[ean_number]" title="<?php echo $block->escapeHtml(__('EAN-Nummer')) ?>"
                   class="input-text required-entry"
                   value="<?php echo $block->escapeHtml($block->getInfoData('ean_number')) ?>" />
        </div>
    </div>
</fieldset>
